#!/usr/bin/env python
# encoding: utf-8


top = '..'

def build(bld):
	if bld.env['WITH_NMIB']:
		for app in bld.path.ant_glob('*.cpp'):
			bld(features=['cxx', 'cxxprogram'],
				source=app,
                target='%s' % (str(app.change_ext('', '.cpp'))),
				use='NDN_CXX',
				includes="../src",
				)


