#!/usr/bin/env python
# encoding: utf-8

VERSION = '0.1'
APPNAME = 'ndn-manage'

top = '..'

def build(bld):
	if bld.env['WITH_NMIB']:
		bld(features=['cxx'], 
				name="nameTypes-objects",
				target="nameTypes-objects",
				source=bld.path.ant_glob('nameTypes.cpp'),
				use='NDN_CXX',
				includes="../src",
				cflags=['-W', '-lboost_serialization'],
				)
		bld(features=['cxx'], 
				name="nmib-objects",
				target="nmib-objects",
				source=bld.path.ant_glob('*.cpp', excl=['main.cpp', 'nameTypes.cpp']),
				use=['NDN_CXX', 'nameTypes-objects'],
				includes="../src",
				cflags=['-W', '-lboost_serialization'],
				)

		bld(features=['cxx', 'cxxprogram'],
				source=bld.path.ant_glob('main.cpp'),
				target="nmib",
				use='nmib-objects',
				cflags=['-W', ['-lboost_serialization']],
				)


