#!/usr/bin/env python
# encoding: utf-8

VERSION = '0.1'
APPNAME = 'ndn-manage'

top = '..'

def build(bld):
	if bld.env['WITH_NMIB']:
		bld(features=['cxx'], 
				name="nmib-objects",
				target="nmib-objects",
				source=bld.path.ant_glob('*.cpp', excl='main.cpp'),
				use='NDN_CXX',
				includes="../src",
				)

		bld(features=['cxx', 'cxxprogram'],
				source=bld.path.ant_glob('main.cpp'),
				target="nmib",
				use='nmib-objects',
				)


